version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: local_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "localpassword"]

  worker:
    build: .
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  beat:
    build: .
    container_name: celery_beat
    command: celery -A tasks beat --loglevel=info
    depends_on:
      - redis
      - worker
      - postgres
    env_file:
      - .env

volumes:
  postgres_data: